language: node_js
node_js:
- '12.14.1'

before_script:
    - npm install

branches:
    only:
    - master

deploy:
    provider: script
    script: npm run build && firebase deploy
    skip_cleanup: true
    on:
        branch: master  