language: node_js
node_js:
- 12.14.1
before_script:
- npm install
before_deploy:
- npm install
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    secure: BiI8wOP1mxaaHyw3cczYyYPu0BmQTduzAwmS3hdAqKg3Gfb6RH851GwF+P/0AfLkYW+7HFQuDdbueag4YeN8USEAqYG0gphWkDpqwl+0DwpHT9vt9OItHj1D01hB3vQx1r82x3mDsyN8N+p04Pg+Co8HMs+fHL7ERK+Ei11OElNA9p9E+kqxzO1wPI+cQq6ssNR+h7wCOZIo1mj+SRTm9RWJMC59CwFD36XZEqMvap1H2D5kdzgswwsTju5yAzdUTDLTWzQgyRJ3nM6xjmNh2FeeUyv5Jv6bTonoA1aeOOTeWYDjOIoV3DDeweJfAgPTvOVrY3RJykKwpoeYZplypbs2Lgq/VE6Sziz6tIHY3kjYLewXq8JTurRezhrTVXAhvLty53ATGoj1NLxkg8tYcIcJiBGoPWeFhnXxWRShoNPa/DPokJZRd0oAdi6urkwchdJX+ZwzaNBw/GvqzhDHSnwgy2Ii2lZuyEfLXlbXZFZzobv2baiASNeKrYoiuOKfMPZJ3n0eZuUrwd+ewx1QvSIc4gZuj+vg+7br4HbN6F34iUM8TmUo484UR1mwOZVcKkbshs6oSDVkWl4iJoSAaK89JFuqwQHQdGo5SN32Hpy1uabKYKVBakU0+UFH/8bq3/A2lOmD6lKp9N2+riMR8/JcWf5tNSIba3HzQhfD+d4=

