language: node_js
node_js:
- '12.14.1'

before_script:
    - npm install

before_deploy:
    - npm install
    - curl -sL firebase.tools | bash

branches:
    only:
    - master

deploy:
    provider: script
    script: npm run build && firebase deploy --token "$FIREBASE_TOKEN"
    skip_cleanup: true
    on:
        branch: master  