language: node_js
node_js:
- 12.14.1
before_script:
- npm install
before_deploy:
- npm install
- npm run build
deploy:
    provider: firebase
    token:
        secure: "dmift01SYQn1ziIUFT/TFEentX/tl0tto2S/cYpbwXL4VtSj2BHcMLTbI/jYh23pKj62WF8x/XVjz0zsFWs5C8/PvgzDVKrvc/6IcEkpbY8sgpSJ5E1H+k2cig2w2H7DztgovcnPQFUPgAYdKJmIWtqTJfjeU5Wp9XbmifH/ZQ4hRSOpkGy9gK0nPhRBMuA8/fYK37kQ2IwPdTD4bAr/rkfqROlt/Q50cE91iOy6/JsG2vIOOUQtn0F3wEuLm1/v76nrqo0n8pjRUuAuKD68EdVrw0hJ1QvcPAQ3qacnY7REgs3PsTeGK0+07c83lEMtyuDnPr+nAnl6jPf+33z2PvLLnkOERevdKVSP7RzxCPSES2w8SK+2LnhcC0AKZocL1cJVRxF5Yd/YvV42jEijoyqZTa0rbwr6ibAXJVFEBFqrZtkDptCpVWIBtsPCruMJI/JNAaaMU+MXlGGJro2FNNDPVnOcF6eW8RCHf1C4dkdc0u6KT/a37DYXpysoinN0z8oHLwoRTUqRO3hQCQtPKTI/yQPQAuQBr4LZ5R6tPXP7hIWDu7aRzBNvOhDMBUIA8Xn+unc6zbnll/Z6+2uL7nT4afxi+/FQCXNTYGdiLu/fruYGvYcM2GnRMya55HH8yGG3YNGOiJx2tgcDuO5lYNIC1JehJcBHOSRUNg5SBa0="

