# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: D'Barros
email: cbsorrilha@hotmail.com
description: > # Meu blog pessoal. Deveria funcionar como um experimento em Jekyll, um lugar onde eu possa escrever coisas legais e também um portfolio. Deveria.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dbarros.me" # the base hostname & protocol for your site
twitter_username:
github_username:  cbsorrilha
exclude: [node_modules]

# Build settings
markdown: kramdown
