# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: W4R Site
email: w4rdevs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Site boladão pesadão dos W4R Developers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  W4RDevelopers
exclude: ['node_modules', 'bower_components', 'js', 'css', '_scss', 'Gruntfile.js']
keep_files: ['_site/css', '_site/js']
# Build settings
markdown: kramdown
